### ISSUE TITLE
Gradle DSL method not found: hugo()

### ISSUE THREAD

**Issue by IgorGanapolsky** [JakeWharton/hugo#104]
Hi,
I am trying to follow your instructions for disabling hugo in Gradle.  I put this in my app's build.gradle file:
`   hugo {
        enabled false
    }`

However, Android Studio is throwing a build error:
> Error:(32, 0) Gradle DSL method not found: 'hugo()'

Please advise how I can correct this.
Igor

**Comment by JakeWharton** [comment]
It's not released yet. It will be in the next version when I get around to
making the final release.

**Comment by maysam** [comment]
:eyes:

**Comment by Gopinathp** [comment]
Hey @JakeWharton, this is not yet released. Any plans on the next release?

This wonderful library becomes less useful if I can't turn off logging in production.

**Comment by ened** [comment]
@JakeWharton kindly release it, thank you

**Comment by JakeWharton** [comment]
No plans to make another release.

**Comment by rpattabi** [comment]
Oh! In that case, I think @DebugLog annotation would be a nice addition to Timber. @JakeWharton Any such plans / work in progress?
