### ISSUE TITLE
Is it possible to use hugo with buck build?

### ISSUE THREAD

**Issue by zhihuawensc** [JakeWharton/hugo#147]
Hugo works fine for gradle build, but when I tried the okbuck, it only picks up the aspectj runtime at '//.okbuck/cache:org.aspectj.aspectjrt-1.8.5.jar', but no debug log was printed from the buck build apk.

I am not sure how to manually enable hugo for buck build either. Is there a way we can support hugo for buck build?

**Comment by JakeWharton** [comment]
Hugo is a Gradle plugin so no it won't work. You can ask the Buck people to write a plugin that does the same thing or someone in the Buck community can do it but it's far out of scope for this project.
