### ISSUE TITLE
There is any issue to combine hugo and apt?

### ISSUE THREAD

**Issue by geovanisouza92** [JakeWharton/hugo#30]
Hello guys, thank you for this tool!

I 've an issue in my app. My build script is:

```groovy
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:0.10.+'
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.2'
        classpath 'com.jakewharton.hugo:hugo-plugin:1.1.+'
    }
}

apply plugin: 'android-library'
apply plugin: 'android-apt'
apply plugin: 'hugo'
```

And I annotated my SyncAdapter-do-all-things method like:

```java
    @DebugLog
    public void make(SyncResult syncResult) {
        // ...
    }
```

But, I haven't see any log in logcat... Any idea about what I'm doing wrong?

Thank you.

**Comment by JakeWharton** [comment]
I haven't seen any issues. If you can create a sample that reproduces something being wrong I'll have a look. Otherwise I'm closing for now.
