### ISSUE TITLE
plugin id is 'hugo', not 'com.jakewharton.hugo'

### ISSUE THREAD

**Issue by fpoyer** [JakeWharton/hugo#48]
Trying to use your (wonderfull, thank you so much for that) plugin in my app. Wrote this (as per your README.md):

``` groovy
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:0.12.+'
        classpath 'org.robolectric:robolectric-gradle-plugin:0.11.+'
        // The following adds the ability to use @DebugLog on methods
        classpath 'com.jakewharton.hugo:hugo-plugin:1.1.0'
    }
}

allprojects {
    repositories {
        mavenCentral()
    }
}

apply plugin: 'com.android.application'
apply plugin: 'com.jakewharton.hugo'
```

Got:

> Plugin with id 'com.jakewharton.hugo' not found

Changed to 

``` groovy
apply plugin: 'hugo'
```

and it worked perfectly!
So either I'm missing a point here (being a complete groovy/gradle beginner, that's quite possible) or you need to update your README

**Comment by adnan-SM** [comment]
Just tried to integrate this and I can confirm it still gives the error. But as the comments say changing 'com.jakewharton.hugo' to 'hugo' works !
