### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Stefantost** [JakeWharton/hugo#56]
The gradle-howto in readme.md is wrong. I needed to do

_apply plugin: 'hugo'_

instead of the 'com.jakewharton.hugo' line

**Comment by kyhule** [comment]
@JakeWharton I am using `com.jakewharton.hugo:hugo-plugin:1.1.0` and I had to use `apply plugin: 'hugo'` as when I used `apply plugin: 'com.jakewharton.hugo'`, I got the following error:
>Error:(13, 0) Plugin with id 'com.jakewharton.hugo' not found.

**Comment by JakeWharton** [comment]
I am aware. For the version on `master`, however, that is not true.
