### ISSUE TITLE
Hugo doesn't work in different debuggable buildTypes

### ISSUE THREAD

**Issue by cesards** [JakeWharton/hugo#66]
I'm trying to use Hugo in different debuggable buildTypes, but it doesn't print anything. Only works with `debug`. Is it not based on `debuggable` var? 

```groovy
prod {
    debuggable true
    signingConfig signingConfigs.debug
}
debug {
    debuggable true
    signingConfig signingConfigs.debug
}
```

Thanks!

**Comment by nono240** [comment]
It seems it happens too if you're using a build flavor.

**Comment by JakeWharton** [comment]
This is already fixed on `master`.

**Comment by cesards** [comment]
![well done 2](https://cloud.githubusercontent.com/assets/1536079/6184101/edd740a8-b35d-11e4-902b-6f8ad0f9ac53.gif)
