### ISSUE TITLE
Hugo plugin requires com.android.tools.build:gradle:0.7.+

### ISSUE THREAD

**Issue by vekexasia** [JakeWharton/hugo#67]
Hello there, 'm unable to use hugo cause of thisdependency :(

**Comment by MariusVolkhart** [comment]
@vekexasia I got the same error tonight without having made any changes. In my case, JCenter was not resolving the metadata correctly. Switching to `mavenCentral()` instead of `jcenter()` for my buildscript's repositories resolved the issue for me. Hope that's helpful.

**Comment by litrik** [comment]
This became an issue for me after updating Android Studio to 1.1 Preview 2.
Switching to mavenCentral() instead of jcenter() does indeed 'solve' the issue.

**Comment by cesards** [comment]
+1 Here

**Comment by asafge** [comment]
+1

**Comment by JakeWharton** [comment]
This is already fixed on `master`.

**Comment by cesards** [comment]
![yeah party](https://cloud.githubusercontent.com/assets/1536079/6184108/0cbef40c-b35e-11e4-8f20-048c858d174d.gif)
