### ISSUE TITLE
Remove + from dependencies

### ISSUE THREAD

**Issue by dalewking** [JakeWharton/hugo#68]
The dependency specified for the gradle build tools is specified as version 0.7+. Dependencies should always specify specific versions not wildcards.

This becomes a problem for me in that our Nexus repo is behind a VPN. About once a day gradle decides to update its + dependencies. If I do not happen to be connected to the VPN what happens is that Android Studio locks up for 3 or 4 minutes trying to update the dependency and you have to either wait or force quit.

The workaround I am using is to add this to buildScript block:

    // The purpose of this is to override the transitive dependency from hugo that specifies
    // 'com.android.tools.build:gradle:0.7+' which forces accessing the remote repo
    configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'com.android.tools.build' && details.requested.name == 'gradle') {
                details.useVersion '1.0.0'
            }
        }
    }

**Comment by JakeWharton** [comment]
There's already an issue for this. Nice hack though!

**Comment by dalewking** [comment]
Actually, I think I started typing the issue before #67 was submitted, just didn't hit submit. But as long as it is covered

**Comment by JakeWharton** [comment]
I promise I'm on it soon. Meant to yesterday but got tied up.

**Comment by cesards** [comment]
@JakeWharton is this hack gonna be applyied finally? Thx!
