### ISSUE TITLE
Lambdas and Method Reference to work with @DebugLog

### ISSUE THREAD

**Issue by ersin-ertan** [JakeWharton/hugo#77]
Just started using Retrolambda and Java 8(request is not specific to Android)

Feature Request: The current functionality, @DebugLog does not trigger with these [two examples](https://gist.github.com/ersin-ertan/b49c8dc3ea7f248a3c33)

Feature Request: @DebugLog to trigger on the lambda standalone:
```java
button3.setOnClickListener((View v) -> {
		 Toast.makeText(this, "test", Toast.LENGTH_SHORT)
			  .show();
	  }); 
```

**Comment by JakeWharton** [comment]
I have no interest in supporting retrolambda. Someone can contribute a fix
if they'd like to, however.

**Comment by promeG** [comment]
@ersin-ertan 

I just create an alternative library [XLog](https://github.com/promeG/XLog) which can work with Retrolambda.
