### ISSUE TITLE
Hugo + Retrolambda - is it possible to use both?

### ISSUE THREAD

**Issue by radzio** [JakeWharton/hugo#78]
Hi,

Thanks for great library. Is it possible to use Hugo with retrolambda? I was trying to use them both in one project without any success. Everything is compiling but I don't see any hugo's logs when I start app. 

I've changed hugo-example app where you can reproduce it ( https://github.com/radzio/hugo/blob/master/hugo-example/build.gradle )

Any ideas / suggestions? 

Cheers,
Radek

**Comment by JakeWharton** [comment]
As I said on #77, I have no interest in figuring out how to support retrolambda. Someone else is welcome to try, however, and I'll merge.

**Comment by radzio** [comment]
Thanks for response. Probably it is retrolambda fault because it's breaking other similar libraries (for example: https://github.com/stephanenicolas/loglifecycle ) 

Another example: https://github.com/evant/gradle-retrolambda/issues/78

**Comment by promeG** [comment]
@radzio 

I just start a pull request to solve this problem.

Also I have updated the example to show how hugo working with retrolambda in my own repo, but I don't think it's appropriate to inlucde this commit to pull request.

https://github.com/promeG/hugo/commit/80fbb188306a50a92177d77f4d82bcc055625607

**Comment by 3mph4515** [comment]
Bump issue.
Does anyone have workaround for weaving libs compability?

**Comment by 3mph4515** [comment]
Bump issue. Does anyone have workaround?

**Comment by promeG** [comment]
@radzio @3mph4515 

I just create an alternative library [XLog](https://github.com/promeG/XLog) which can work with Retrolambda.

**Comment by evant** [comment]
I've tested hugo support with the latest version of gradle-retrolambda (3.1.0) and it seems to be working fine. I changed it to do way less bad things to the javaCompile task which should increase compatibility with other plugins like this one.

**Comment by 3mph4515** [comment]
@evant Awesome. Thanks!

**Comment by JakeWharton** [comment]
Well shit I just merged a thing to change when our AspectJ is run (it's now immediately before dex). I can't imagine it'll hurt, at the very least!

**Comment by mwatel** [comment]
I confirm Hugo 1.2.1 does not log a thing when using retrolambda. [https://github.com/promeG/XLog](XLog) works like a charm if you are using retrolambda. Thanks a lot @promeG!
