### ISSUE TITLE
Add a 'verbose' parameter to @DebugLog which en-/disables the logging

### ISSUE THREAD

**Issue by seifferth** [JakeWharton/hugo#82]
I would like to be able to give @DebugLog a parameter which en-/disables the logging. I don't wan't to see all logs everytime. So eg. if I'm interested in the api logs I would adjust my verbose constant to see them and if I'm interested in other parts I can disable them (to don't be distracted).

**Comment by JakeWharton** [comment]
Couldn't you just comment out the annotation to the same effect?

**Comment by seifferth** [comment]
It would have the same effect, of course. But it's not my understanding of clean code and working efficiency to (un-)comment multiple lines of code instead of using one constant for it.

What's why there exists Hugo, isn't it? At least it would have the same effect to do a manually log in each method too. But it's not as clean and useful as the @DebugLog approach.




> Am 13.05.2015 um 17:17 schrieb Jake Wharton <notifications@github.com>:
> 
> Couldn't you just comment out the annotation to the same effect?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

-- 


http://smartmobilefactory.com/

Smart Mobile Factory GmbH, 

Französische Str. 24, 10117 Berlin 

Sitz: Berlin, Amtsgericht Charlottenburg, Handelsregister Berlin HRB 124077 
B, Geschäftsführer: Rüdiger Weiß, Dr. Leif E. Göritz

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte 
Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail 
irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und 
vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte 
Weitergabe dieser Mail ist nicht gestattet.

This e-mail may contain confidential and/or privileged information. If you 
are not the intended recipient (or have received this e-mail in error) 
please notify the sender immediately and destroy this e-mail. Any 
unauthorised copying, disclosure or distribution of the material in this 
e-mail is strictly forbidden.

**Comment by JakeWharton** [comment]
I think I'll move the `Hugo` class into the public API and give it some options including a log hook for #60

**Comment by JakeWharton** [comment]
And, obviously, a setting for this

**Comment by JakeWharton** [comment]
`Hugo.setEnabled` just merged.
