### ISSUE TITLE
Add support for Trace.beginSection/endSection

### ISSUE THREAD

**Issue by yogurtearl** [JakeWharton/hugo#83]
Not sure if this is in the scope of Hugo, but have an annotation for wrapping methods in Trace.beginSection/endSection would be very helpful.

Maybe a parameter to @DebugLog?  @DebugLog(trace=true)
Maybe a separate annotation ( @DebugTrace ) ?

output would function like: 
```java
class Bar{
  void foo(int snarg){
     if( SDK_INT >= 18 ){
            Trace.beginSection("Bar.foo(snarg="+ snarg+")")); 
      }
      try {
             <method_body>
      } finally {
         if( SDK_INT >= 18 ){
             Trace.endSection();
         }
      }
  }

}
```

**Comment by JakeWharton** [comment]
What about always doing it for annotated methods? Too much?

**Comment by yogurtearl** [comment]
From a quick glance at the code, it looks like Trace is low overhead when you are not actively tracing:
https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/os/Trace.java

So always-on Trace'ing for @DebugLog might be OK. If it becomes a performance issue, can always add a way disable it later.

**Comment by JakeWharton** [comment]
Want to send a PR? Otherwise I can do it at some point in the next week or two.

**Comment by yhartanto** [comment]
@yogurtearl @JakeWharton  see if you guys like this one. https://github.com/JakeWharton/hugo/pull/86

**Comment by yhartanto** [comment]
@JakeWharton, I updated the previous PR. It is always enabled now. https://github.com/JakeWharton/hugo/issues/83

**Comment by JakeWharton** [comment]
Merged. Will squeeze out a release in the next two weeks.
